### ISSUE TITLE
Let's Get Started!

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#1]
Hi guys! I'm really excited my project idea was chosen and first off I wanted to thank you for joining me. Now, I'd like to think about some ideas we could implement for the project and get a feel for what _exactly_ we would like to create, as well as where we can go to get our sources and what we can do with them. Jamie, I know you told me you weren't very familiar with who Tesla was, and Aaron I'm not certain if you are familiar with him either, so I think a good place to start would be to research he and Edison and get some basic history about the time period under our belt. I'll link some good sources here for our reference.

I find that biography.com is a great unbiased source of information about people, and I cite it quite often: [Tesla](https://www.biography.com/people/nikola-tesla-9504443) ; [Edison](https://www.biography.com/people/thomas-edison-9284349)
and
I would be careful about using this as a source for obvious reasons, but the Wikipedia articles are pretty extensive and may help if you browse through them a bit: [Tesla](https://en.wikipedia.org/wiki/Nikola_Tesla) ; [Edison](https://en.wikipedia.org/wiki/Thomas_Edison)

**Comment by dotfig** [comment]
I think the first question we have to answer is what we want to do with this project. What did you have in mind @quantum-satire? What articles are we trying to mark-up and what is our final goal of this project?

**Comment by helvitiis** [comment]
@ajnewton1 I originally had some ideas in mind on my initial project proposal, which I'll quote myself on here:

> [The] initial idea for this project was to scour the internet for texts, journalistic publications, and newspaper articles about Nikola Tesla versus Thomas Edison in the AC/DC "War of Currents" (AC stands for Alternating Current and DC for Direct Current). We could then read through each piece of text and mark up locations cited to create a map of the hotspots where electricity hosted its earliest years, and to see who was mentioned the most for the public eye. I'd also like to take a look at the major differences between the two currents, marking up definitions of the original patents or published articles explaining what each does and how they work. However, I can understand this part may not be the paramount of excitement for everyone, so I'm also proposing the possibility of logging which person was mentioned more times in newspapers and journals, what the overall mood of that piece was (was it shedding a positive or negative light on the person in question; what adjectives were being used to describe that person; was the piece propaganda, etc.) and other creative ways to show, in the end, who was more popular for which reasons. We can read a great number of books about these two, but being able to show their differences is what will really make this project unique!

I think that this could be a good start! We could begin with newspapers and public journals that mention them or their work, and I can try to find a way to acquire the original patents and take a look to see if they would be interesting enough to markup the differences between them. I'd also really like to get any ideas you or @Jamielynn92 might have too!

**Comment by ebeshero** [comment]
@quantum-satire This looks like a potentially useful resource (and I imagine you probably know it): It appears to be a pile of largely uncategorized articles about Tesla, and you can sort them by the chronological order in which they were published: https://teslauniverse.com/nikola-tesla/articles The articles seem to be in digital form so you wouldn't have to transcribe them.

**Comment by helvitiis** [comment]
@ebeshero This is insurmountably helpful, thank you! @Jamielynn92 @ajnewton1 We can look through these and pull any that might be relevant to the period we are looking for into a space on our hub. I'm going to make a special folder for collecting resources like this that we can use. If we place a file into the folder, let's try to keep the URL with the source so that we can reference the original source later!

**Comment by dotfig** [comment]
@quantum-satire I saw that you made a folder and put the format inside of it. Do you think maybe we should make a schema for this and then that way all the documents that we mark-up would be for certain the correct format 

````
start = document
document = element document {publisher, date, filetype, title, author, url, text}
```` 
You get the idea. This is good so when we associate the schema to our XML, everything would look neat and organized. Plus, we could use Regex to find any specifics easily.

**Comment by helvitiis** [comment]
@ajnewton1 This is a good idea! I think I went ahead and made the format the way I did in the folder just to compile some potential material before we actually code them. That way we wouldn't have to spend more time on marking up materials we may not use--but it's a good idea to write the schema, so I'll make a start on it tonight and post what I have on this hub so we can work from it as a team!

**Comment by dotfig** [comment]
I saw that you uploaded the schema, looks great! 

- [x] Schema

- [x] Webspace Name

We need to think of a name for our website. I personally think 'ac-dc' could be easily confused with the band AC/DC but maybe its just me. We should decide soon so @ebeshero can create us a directory so we could start adding pages to our site.

warofcurrents.newtfire.org

Edit this comment to add any ideas that you ( @quantum-satire @Jamielynn92 ) come up with. Also put your first two picks, like we did in class regarding project topics, in square brackets.

**Comment by Jamielynn92** [comment]
I like the teslavsedison one. Maybe because i don't know how many people are aware of the name ac-dc. (Like me) I was unaware that was what he was known for. But I'm excited to learn more about it. Although the warofcurrents is clever cause it pulls you in a bit. But it is a bit obscure on what the topic is.but I know small details. So I shall learn about it as we go.

**Comment by helvitiis** [comment]
Unfortunately I am on mobile and unable to edit the comment directly, but I really like warofcurrents.newtfire.org as my first pick and teslavsedison.newtfire.org as my second. Those are great—I emailed Dr. B earlier today but I’ll see if we can use one of these instead—I like these a lot better!
