### ISSUE TITLE
Color Scheme and Banner

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#10]
![warofcurrentsbanner](https://user-images.githubusercontent.com/28074589/31572272-fdc4eea4-b06f-11e7-8ee4-5905d110bf76.png)
![colorscheme](https://user-images.githubusercontent.com/28074589/31572273-ff174c66-b06f-11e7-828d-fccc591d7f8b.png)
Still working on the design, but I thought I'd post what I have so far to get some input from you guys. I pulled the colors straight out of 1890s advertisements and used a recreation of a vintage font from the proper time period. (Please tell me if you straight up don't like it or feel like something could be changed to make it look better--you won't hurt my feelings!)

I'll be getting around to updating the schema as well tonight!
EDIT: Schema is [now updated!](https://github.com/quantum-satire/warofcurrents/blob/master/resources/schema.rnc)
@ajnewton1 @Jamielynn92

**Comment by Jamielynn92** [comment]
I like it.

**Comment by dotfig** [comment]
I like it too! Where did you have in mind to put the lightning bolt at?

**Comment by helvitiis** [comment]
@ajnewton1 Not particularly on the page, but just to show the colors together as an example of how they work together! I'm thinking of #F2DC9A (light beige) as the background, with #123C56 (dark blue) as links and accents and #D8A244 (faded sienna) as the text color. There was one other color I thought we could fit in as an accent color if need be-- #f14016 (bright orange) --shown here:
![14-1910s-usa-willys-overland-magazine-the-advertising-archives](https://user-images.githubusercontent.com/28074589/31572444-071dd61a-b074-11e7-9b80-568a52b189e4.jpg)
It may be too much, but it's a good contrast with the blue. I think if it would be used at all, it should be sparingly...

**Comment by Jamielynn92** [comment]
I like that idea as well. It gives it a nice pop of needed color. Cause you got some brown tones and dark blue so the orange will draw your eye a bit with interest.

**Comment by helvitiis** [comment]
The fonts I used are also here, just for reference if we want to use them elsewhere on the site:

[FHA Tuscan Roman (Spurred) by the Fontry](http://www.fontspace.com/the-fontry/fha-mod-tuscan-roman-ncv)
[Brev Script by Måns Grebäck]()

**Comment by dotfig** [comment]
@quantum-satire I added the logo to the website. I am going to try to make the padding/ spacing to be tighter tomorrow so it looks better. Right now the menu bar looks like its to far down. Ill try to fix that

**Comment by helvitiis** [comment]
@ajnewton1 I can also trim the transparent pixels tighter around the image--I'll do that right now for you and slip it into the website files to see if that helps.

**Comment by helvitiis** [comment]
@ajnewton1 Done!
