### ISSUE TITLE
Issues with New Code

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#11]
Here's something odd: the code changes in the CSS and HTML I pushed to the server will run on http://firebellies.newtfire.org/warofcurrents/ but not on http://warofcurrents.newtfire.org

Am I doing something incorrectly here? This hasn't happened before that I'm aware of.

@ebeshero @ajnewton1

**Comment by ebeshero** [comment]
@quantum-satire They both look the same to me right now...What should I be looking for?

**Comment by ebeshero** [comment]
@quantum-satire Sometimes CSS takes a few minutes to "catch" when it changes...I wonder if there was just a delay in the CSS being applied on the http://warofcurrent.newtfire.org address?

**Comment by helvitiis** [comment]
@ebeshero Here are the differences for me:
![screen shot 2017-10-14 at 10 10 38 pm](https://user-images.githubusercontent.com/28074589/31580977-955345f6-b12c-11e7-8895-5b170e5d11d9.png)
![screen shot 2017-10-14 at 10 10 11 pm](https://user-images.githubusercontent.com/28074589/31580978-96bb72b0-b12c-11e7-9205-a3b3f785e0a5.png)
I restarted my web browser and cleared the cache files, so I thought it was odd that they were showing up differently; it only seems to be the CSS that isn't registering.

**Comment by ebeshero** [comment]
@quantum-satire Hmmm... For me, they still look the same, and http://warofcurrents.newtfire.org comes out like this: 

<img width="1290" alt="screenshot 2017-10-14 22 16 01" src="https://user-images.githubusercontent.com/4014518/31581005-6a815a4c-b12d-11e7-9f3d-393ea4477b53.png">

**Comment by ebeshero** [comment]
@quantum-satire Try a different web browser?

**Comment by ebeshero** [comment]
By the way, the CSS looks terrific!

**Comment by helvitiis** [comment]
@ebeshero As long as it works on your end, it must be my computer that's acting up. I tried both Safari and Chrome to view them... I'm going to keep playing with it until I can get it to work. Thanks for letting me know--I appreciate it! And thank you! Aaron and I have been working on it for a bit!

**Comment by ebeshero** [comment]
@quantum-satire It's funny that it's registering on one address for you but not the other--clearing your browser history **should** have worked. Try taking a look at it on a mobile device, too.

**Comment by helvitiis** [comment]
@ebeshero That is so odd--it's working just fine on mobile. It may be an update issue, I did load some major updates within the past few hours so perhaps restarting again could fix it.

**Comment by helvitiis** [comment]
@ebeshero That and clearing the cache files again seemed to fix it!
