### ISSUE TITLE
"About Me" Page

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#15]
@ajnewton1 I made a start on the team "About Me" page--do you know how to link this with the menu to be a drop-down feature? I figure I'd leave that up to you when you get a chance as you know more about that than I do!

**Comment by ajnewton1** [comment]
@quantum-satire Yes I can get to that. Check your Pitt Email

**Comment by dotfig** [comment]
@quantum-satire I just updated the about me page. I am going to insert the same code in the index so be careful. Do a git pull in a few minutes

**Comment by dotfig** [comment]
@quantum-satire somehow my access to publish anything to our web server got revoked so I am unable to update anything. @ebeshero

**Comment by helvitiis** [comment]
@ajnewton1 What is it saying, exactly?

**Comment by dotfig** [comment]
@quantum-satire 'Fetch could not put "about.html" because the SFTP server says you do not have the required permissions." I am not sure if this is something you can fix or if Dr. B has to fix it.

**Comment by helvitiis** [comment]
@ajnewton1 Let me try something, I might be able to fix the permissions for the file

**Comment by helvitiis** [comment]
@ajnewton1 Try again and see if that worked. You may want to disconnect and reconnect again

**Comment by dotfig** [comment]
@quantum-satire no I am still not able to

**Comment by helvitiis** [comment]
@ajnewton1 I'm going to delete the file from the server and see if you can upload it from your computer

**Comment by helvitiis** [comment]
@ajnewton1 It looks like that worked on my end--did it work on your end?

**Comment by dotfig** [comment]
@quantum-satire This is being weird... yes it worked. try to go through each document, right click -> Get info -> then change the permissions to read write execute for all of them except the last one

What I have to do in order to add a file would be to delete the original then add my file in replace

**Comment by helvitiis** [comment]
@ajnewton1 I went through and made sure they were fixed, hopefully it doesn't act up again. That's odd that it did that, though

**Comment by dotfig** [comment]
@quantum-satire what're your thoughts on the "Home" page? Do you think maybe we should give them background information on AC current, DC current, main figures (Tesla, Edison), and stuff like that

**Comment by helvitiis** [comment]
@ajnewton1 I need to do a full write-up of the history still, which may take me a while, but I'll get on it as soon as I have time!
