### ISSUE TITLE
xml:id Usage

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#17]
@ebeshero Is there a place I can go to read about the correct usage of xml:ids? I looked through Obdurodon and Newtfire and didn't find what I'm looking for. I'm a bit confused as to how to define them and then, for example, tag them in the bodies of texts when marking `<persName>`, `<event>`, or `<loc>`, etc.

**Comment by dotfig** [comment]
@quantum-satire If I am not mistaken, you define your xml:id attribute first and then when other instances come up, you use ref attribute. For example:

````
<persName xml:id="Tesla_N">Nikola Tesla</persName> was doing many experiments in the past
month.<persName ref="#Tesla_N">Tesla</persName> and <persName
xml:id="Edison_T">Edison</persName> are known for conducting 'magic' in the streets of New York
City. Actually, <persName ref="#Edison_T">Thomas Edison</persName> was often referred to as the
<persName ref="#Edison_T">Wizard of Menlo Park</persName>.
````

You see here that when we first see a person, we use `<persName xml:id="Example_1"></persName>` and then when we see that same person again, we use `<persName ref="#Example_1 "></persName>`

**Comment by ebeshero** [comment]
I'd recommend that you all pull the distinct-values() of your people names, and output those in XML (as and XML to XML transformation)--make a list of elements. If you want to borrow a little from TEI, you can be inspired by their personography markup! Holding a separate file organized with information about each person has multiple purposes (which we discussed just now in my office, and you can explain to your teammates).

Imagine a structure to hold the person information--it doesn't need to be that detailed at first, but what about something like this?
```
<listPerson type="historic">
<person xml:id="mustHaveLettersMaybeNums">
     <persName>Thomas Alva Edison</persName>
     <persName>Tommy Boy</persName>
      <persName><surname>Edison</surname>
                            <forename>Thomas</forename>
                           <forename>Alva</forename>
      </persName>
     <birth date="yyyy-mm-dd"/>
     <death date="yyyy-mm-dd"/>
     <note resp="#projTeamMember">Write some pithy note here that you'd want to output on your website about this person and their connection to the War of Currents.</note>
</person>
</listPerson>
<listPerson type="projectTeam">
     <person xml:id="qs"><persName>Allyson Hall</persName>
     </person>
</listPerson>
```
In your other files you *point* (as @ajnewton1  indicated) to the xml:ids stored in the personography with a `@ref=#id` with the hashtag working very much as a way to generate (in output HTML) an internal linking mechanism--> you can output this with a web URL followed by #id, to land you on an HTML output page with your personography info.
@quantum-satire

**Comment by ebeshero** [comment]
By the way--this is long range stuff. Concentrate on marking up all the persNames for now!

**Comment by helvitiis** [comment]
[Here](https://github.com/quantum-satire/warofcurrents/blob/0d299d68ee81c68b83b6ab99bfd818b2166705ef/resources/idSheet.xml) is our xml:id sheet. It'll continue to grow the more people we encounter in our documents!
