### ISSUE TITLE
Site Connections and Team Meetings

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#2]
Hi guys! I spoke with Dr. B and she has our website directory up and running. I want to make sure we all have our local computers set up to access it through FileZilla (or Fetch) with no issues--the directory name is `warofcurrents` and our remote site is `/var/www/html/newtfire/warofcurrents`. Also, remember to clone this repo to your local computers!

I also wanted to see when would be the most convenient times for us to meet as a group. Usually, I am the most free on Fridays after 12:30 where I can meet any time. Jamie, I know you're usually free after 12:30 as well on Fridays, so Aaron that may work if you aren't busy between 12:30 and 2 (Jamie has a class at 2). I work in the Learning Center in the library, and it's almost always empty around this time, so it could be the ideal place to meet. Let me know what works so we can get this going!

@ajnewton1 @Jamielynn92

**Comment by Jamielynn92** [comment]
Hey @quantum-satire I sent you an email. Lol.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dotfig** [comment]
I work right after class so I wont be able to on Mondays/Wednesdays/Fridays. How're you schedules on Tuesdays/Thursdays? @Jamielynn92 @quantum-satire

**Comment by helvitiis** [comment]
@ajnewton1 Tuesdays and Thursdays are my busier days, I start at 8 am and go until 5 pm. The only free time I have is between 10 am and 1 pm, and usually I try to get home as soon as possible after my last class to take care of my family, so I wouldn't be able to stay after 5 pm. Ideally, I could shoot for a meeting time of 12 - 12:50 on a Tuesday or a Thursday. I can also meet on Saturdays if we need to, but I work all day on Sundays.

**Comment by dotfig** [comment]
I can meet at that time on Tuesday/Thursday @quantum-satire

**Comment by Jamielynn92** [comment]
Tuesday and Thursday I'm off. But I have class @ 12 and 1.

**Comment by helvitiis** [comment]
What about Tuesday or Thursday at 10?

**Comment by dotfig** [comment]
I can do Thursday at 10 in FOB 131 if that is good with everyone? @quantum-satire @Jamielynn92

**Comment by helvitiis** [comment]
@ajnewton1 That works for me!

**Comment by Jamielynn92** [comment]
I could do that.

**Comment by jonhoranic** [comment]
@Jamielynn92 @ajnewton1 @quantum-satire 
Hey hey, getting organized and ready I see! Let me point out a few little things for you. Aaron, this stuff is going to look familiar from working on a project team before, so no doubt you can give your team some input on these as well!

1. Be on the lookout for the availability of your documents! Digital resources will be the most effective, both for saving time and to minimize the workloads. If you end up with physical records you will have to spend effort on transcribing. 

2. I would recommend making task lists or open separate issues for each resource/paper (or however you wish to group them) so you do not get swamped with files. Making sure everyone is on the same page with what is done or not is VERY important to avoid merge conflicts and other stressors!

3. Organize as best you can! Build a good file management system for the repo! Note: GitHub will NOT display empty folders, you will have to place a file inside for it to be visible in the web interface! When I make new folders, I place a dummy file inside that I will edit and rename later just so I can get my "filing cabinet" all laid out first.

**Comment by helvitiis** [comment]
@jonhoranic Thank you for the advice!
@ajnewton1 @Jamielynn92 Are we meeting today for our first meeting?

**Comment by Jamielynn92** [comment]
Yea. I'll be there.

**Comment by helvitiis** [comment]
@ajnewton1 @Jamielynn92 I may be a few minutes late, my class is running over and I'm in Smith!
