### ISSUE TITLE
Updating Website

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#20]
Hey @ajnewton1 ! Do you think you would be able to put a button on the menu that navigates to the index (home page)? I just now realised we don't have one--and it would probably be good if we did. I'd do it myself, but I don't want to mess with your portion of the code and potentially have it go haywire.

Also, I'm finishing up some stuff for the website tonight and I'll be pushing that into the repo / server soon, so it may be easier to wait until I do that until editing any more of the code.

**Comment by dotfig** [comment]
@quantum-satire Actually I didn't think we needed one for the index. If you click the War of Currents title it should take you back to the home page. I could add one tomorrow if you feel like I should however.

Is it possible to convert the image to an svg with Adobe? Or do you not think it will be a good idea?

**Comment by helvitiis** [comment]
@ajnewton1 I can look at trying to convert the image to svg, but I haven't done that before. I'll let you know once I find out!

Also, I think it might be good to include a home navigation button in the menu just for user convenience. Some users may not know to click the icon to return home!
