### ISSUE TITLE
Tasks (11/30/2017)

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#24]
- [x] The **TOC needs to have the links pointing to the texts** hosted on their own .html pages. @ajnewton1

- [x] We're working on **adding `@ref attributes`** to the document code. @quantum-satire

- [x] Add a GitHub link leading to our repo on our website. @ajnewton1
- [x] I'm going to be working with the xml code once the files are hosted on their own pages. Some of the things I'll be marking are:
    - Names and corresponding colors according to xml:id. (Ex. All `<persNames>` marked with the xml:id "#Tesla" will have `style="color:teal"` applied.)
    - Places and creating links to a new .html page I'll be making explaining the significance of certain areas / places relevant to the War of Currents.
    - Looking at dates and date ranges for our timeline

- [x] Thinking about a **timeline**... I'll try and put something together for this. It'll probably be for the best if it's static rather than interactive.
![img_2139](https://user-images.githubusercontent.com/28074589/32907065-de59beba-cacc-11e7-8f45-02519424b336.JPG)
Wow that is sideways, alright. Thanks GitHub

Anyway, we have two weeks to do this (until the 30th). We can get this done!

**Comment by dotfig** [comment]
Links on website are done. I will add the text on each page once the `@ref attributes` are completed. I will also alphabetize them soon.

**Comment by helvitiis** [comment]
@ajnewton Sounds good!

**Comment by helvitiis** [comment]
@ajnewton1 Everything is updated now, including @ref attributes and the schema. You should be able to host the documents now. Let me know when you've gotten that done and I'll get to editing the HTML / CSS for the pages!

**Comment by helvitiis** [comment]
@ajnewton1 How does [this](http://warofcurrents.newtfire.org/timelineIndex.html) look for our timeline? Will be adding more entries to it soon, or I'll have @Jamielynn92 help me.

**Comment by dotfig** [comment]
@quantum-satire Im not really a fan of the timeline. It doesn't really match the website and its impossible to read unless you stop at the right spot on the page

**Comment by Jamielynn92** [comment]
I’ll look at it later. I’m stuck at work til 6:30.

**Comment by helvitiis** [comment]
@ajnewton1 I spent a good few hours on it yesterday but needed a break and uploaded what I had, I'm still working on the padding and functionality as I adapted it from another opensource timeline project. I just know we need something for the timeline page. I haven't added our banner icon to it yet either, I just ran out of time. I'm going to keep working on it, unless you wanted to try your hand at making a timeline that worked better with our theme?

**Comment by helvitiis** [comment]
@ajnewton1 I changed the timeline so it isn't as buggy or ugly. Also, I saw that you linked the GitHub repo at the bottom of all of the pages--do you want me to replace the text with an SVG image of the GitHub icon instead? I have one we can use

**Comment by dotfig** [comment]
@quantum-satire Sure that'll work. 

Actually about the timeline page. It looks really good but we are not allowed to use jQuery or any other JavaScript libraries. Read [Project Guidelines](http://dh.newtfire.org/projectGuide.html) just to make sure everything else were doing is good to go!

**Comment by helvitiis** [comment]
@ajnewton1 If I make all of the entries for the timeline, do you think you would be able to adapt the code to make it look presentable without using jQuery? I did change a bit from the source code already, so I'm sure it could be adapted further to fit what we need. If not, I can get around to it, but it may not be for a while. Just let me know--I'm going to be tackling the SSI for all of the pages next, then figuring out a way to present our results graphically (text boxes that appear on mouseover on document pages for example).

**Comment by dotfig** [comment]
@quantum-satire Yea I will see what I can do but I am sorta in the same boat that you're in. I have been busy lately so I cant give you an exact date to when I can get to it.

**Comment by helvitiis** [comment]
@ajnewton Yeah of course! It’s a holiday break so I totally understand. Let me know how it goes when you get around to it and if you need any help
