### ISSUE TITLE
new XSLT to generate HTML for documents

### ISSUE THREAD

**Issue by ebeshero** [quantum-satire/warofcurrents#26]
@quantum-satire @Jamielynn92 and @ajnewton1 : Aaron was with me and advised as I was working on this: I prepared an XSLT file that is as yet unfinished. It is currently doing what we did in the homework XSLT Ex 5 and 6 with the input collection of poem files, to output them to HTML, but the output right now is [**one** HTML file](https://github.com/quantum-satire/warofcurrents/blob/master/website/allDocuments.html), with each article separated in its own `<div>` element with its own distinct `@id` attribute based on its pubDate. This was just the easiest way to output everything quickly. 

Aaron thinks that might be something worth working with in its own right--that you might want all your output to be in one HTML document, and you could combine that with your table of contents to hide them all, and show them on click. That could work! 

Alternatively, we can run another process to split the output into multiple files, and there a few different approaches:
* One approach, which I forgot to mention @ajnewton1 , is a second XSLT process that splits each article into its own new HTML file (but we need to write that--it's not hard, but I want you to see it if we do that). 
* Another is to run this XSLT file in your shell (but I need to show you how to do that). It's not hard, but you need to know what you're doing! I think I like this option best.
* The last is to work with oXygen projects inside oXygen: create a project, and control the output. We did this with the Hamilton project last spring. It's not as simple as the other two--but has the advantage of working inside oXygen. Really, I think one of the first two approaches is better--less clunky and difficult to implement. 

No matter what approach you decide, basically we're overhauling how you're outputting the HTML, so that it's easier to write simple commands just *once* in the relevant SSI, CSS, or JavaScript file, and so that your output is going to be **valid** HTML. Right now, the HTML output is not well-formed, but the tags are good HTML tags (not XML embedded in HTML). We're also trying to minimize/eliminate any inline CSS and JavaScript that you'd be tempted to implement manually. We can go over all this together the next time I see you (perhaps this afternoon? Perhaps Monday). I'm out of class at 3pm and will be in my office in FOB 204 if you want to come find me for a bit.

**Comment by ebeshero** [comment]
@quantum-satire @ajnewton1 @Jamielynn92 The XSLT file is here: https://github.com/quantum-satire/warofcurrents/blob/master/website/documentToHTML.xsl

Aaron and I decided to destroy, nuke, and otherwise lay waste to the "documents html" directory, since it had old problematic code in it. Consider that for the moment to be replaced by the single HTML file containing all document output: 

Aaron is in favor of having all the documents be output at the same level so that we don't have to worry about referencing their CSS and JavaScript in a parent directory (which is going to cause confusion). That makes sense, but if you *do* want to store your documents in separate HTML files I think I'd advise keeping them in their own directory, having them reach **up** to a parent directory for CSS and JS and SSI files from the main site, just because these are a special *set* of documents that you'll be automatically outputting with XSLT (differently from the way you'll be updating say the index or about.html pages by hand). If you decide to leave the output in one giant HTML file, though, it's not so much an issue.

**Comment by ebeshero** [comment]
@quantum-satire @ajnewton1 @Jamielynn92  IMPORTANT: I did not finish the XSLT, and we did not try putting the HTML all-documents-in-one output file up on the web server. When I say I didn't finish it, I mean, that I only output basic things like your structure, and I implemented just two HTML `<span>` elements. One was to control the author byline (for which you may want to write CSS), and the other was just to transform the `persName` elements into `<span class="persName>`. You can and should add template rules following my lead for any other elements mixed into your paragraph content that you need to be toggling with JavaScript and highlighting with CSS.

**Comment by helvitiis** [comment]
@ebeshero @ajnewton1 Thank you for helping us with this! I'm sorry I had to leave so quickly and couldn't stay to give any input on it. I have a few questions:

1. Can we still add ids to the `<span>` elements even if the original xml documents folder was wiped out from our site? i.e. `<span class = "persName" id = "Edison">`.
2. When we add JavaScript to toggle names, places, locations, etc. will it mark _all_ of the documents or one at a time? And, can we apply a count() function to each individual document?
3. Can we include a "show all" toggle button that will open all of the documents at once on the page? Also, will it look too chaotic to have all of the documents open at once / will it negatively affect loading time?
4. What are the differences between the processes you listed above in your first comment? I'm also agreeing with Aaron that it seems to be the best and easiest choice to output all of the files on one level at this point--it was getting a little chaotic trying to figure out what to do with all of the HTML pages holding the documents.

On more of a lesser side note here regarding color choice--I think at this point it would be easiest to keep the colors we have now as I realized the art I made for the front page as well as the graphics and the logo uses the color scheme we have now, and after locally changing the background color it looks silly. I'm thinking about making the font bigger or finding a different font if it seems to be a big issue with legibility of the documents, and it seems that the only visibility issue so far is with dim projectors and outdated or non-color-managed monitors.

I have work from 11:30 to 1:30 on Monday, but I think it's important to have a meeting to discuss the project if possible. Is there a convenient time that day (or the next) we could do this?

**Comment by ebeshero** [comment]
@quantum-satire On the first question:

> Can we still add ids to the `<span>` elements even if the original xml documents folder was wiped out from our site? i.e. `<span class = "persName" id = "Edison">`.
 
I'm a little confused by this. The only thing we eliminated was the folder named "documents html", which contained only html files. The XML we used as a source is the "documents" directory which appears to be unchanged. I'm taking a look, for example, at https://github.com/quantum-satire/warofcurrents/blob/master/website/documents/NP1891-02-20.xml , and the XML contains information from which you could easily write an xsl template rule to output HTML span elements with `@id` attributes as you suggest. (Please do that by building on the XSLT file we worked on, and not with regex. The XSLT should help to plan how you're mapping from XML to HTML, so the encoding actually serves as documentation!)

**Comment by helvitiis** [comment]
@ebeshero Whoops! Alright, I misunderstood which folder you had deleted. Thanks for the clarification!

**Comment by ebeshero** [comment]
@quantum-satire On the other three questions--we'll want to talk about and experiment with the possibilities, and the longer meeting you suggest is a very good idea--perhaps Tuesday afternoon if everyone is available? Briefly though:
* We'll easily be able to split the giant single output HTML file into separate files (I want to show you the details instead of typing it up here--that's easier done in person). It might be worth considering the advantages and disadvantages of either approach. Really, we could output BOTH ways and experiment a bit with whether the files are more manageable as separate pieces or as a single unified document. 

*  A JavaScript show-hide function could hide all the articles, and perhaps expose just one default on load of the page. On click of a title in the table of contents, anything previously showing can be hidden, and *this* currently-clicked-on file could show. 

* An interesting possibility might be to apply JavaScript to reveal *clusters* of articles that have related content: That might involve outputting a class on the `<div>` element we've set around each article...something to think about! And there will be other possibilities. 

At this stage, it's time to play a bit with the XSLT (and make new XSLT files from it) to experiment with outputting different combinations and remixes that show interesting patterns... Survey your code and think about what would be interesting to list, chart, or summarize from it...

**Comment by helvitiis** [comment]
@ebeshero I had been planning on making a map using the marked `<loc>` elements, but I know we wanted to do a lot more with the code. Can we log marked elements such as `<persName>`, `<current>` and `<company>` and show corresponding responsive SVG charts beside each document, as well as an overall count? (My only worry about this is the amount of time we have left to do it)

I can meet Tuesday after SF if that's convenient for you!
@ajnewton1 @Jamielynn92 this would be about 2:20 pm on Tuesday.

**Comment by ebeshero** [comment]
@quantum-satire You can, and you should give it a try! There's time enough. :-)

**Comment by dotfig** [comment]
@quantum-satire I have class during that time but I can see what I can do. Where would this be?

**Comment by helvitiis** [comment]
@ajnewton1 It would be in Dr. B's office in FOB

**Comment by Jamielynn92** [comment]
I can meet after English tomorrow.

**Comment by helvitiis** [comment]
@Jamielynn92 What time would that be?

**Comment by ebeshero** [comment]
@quantum-satire @Jamielynn92 @ajnewton1 I just realized I have a faculty meeting tomorrow from 2:30 - 3:30 pm--but I can meet around 3:30! Does 3:30-ish work at my office, FOB 204? (We can move downstairs to the Center room for more space if the whole team is there.)

**Comment by helvitiis** [comment]
@ebeshero I can meet at 3:30!

**Comment by Jamielynn92** [comment]
I can. Just gotta figure out what to kill an hour. I get out at 2:15

**Comment by Jamielynn92** [comment]
How to kill an hour. Lol my bad.

**Comment by ebeshero** [comment]
Let's move this (since it's a project meeting) down to the Center in FOB 131. You can let yourself in by punching in the sequence of odd numbers. And I'll see you at 3:30pm.
