### ISSUE TITLE
Map & Linking

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#27]
@ajnewton1 Do you think you could link the [map](http://warofcurrents.newtfire.org/map.html) in the JavaScript portion / menu? It would have its own tab right beneath "Timeline" in the Analysis portion of the menu. I don't want to mess with it and potentially break it. Thanks!

**Comment by ajnewton1** [comment]
@quantum-satire We will talk about this tomorrow so I have a better understanding of what you want

**Comment by dotfig** [comment]
@quantum-satire done

**Comment by dotfig** [comment]
@quantum-satire Are you able to fix your inline css on the map page

**Comment by helvitiis** [comment]
@ajnewton I used inline CSS in this case because it contained flexbox work only pertinent to the map page and no other page. Do you mean for me to fix the CSS in a separate file?

**Comment by dotfig** [comment]
@quantum-satire We need all of our css inside a separate file. [Unless there is a good reason that you have cleared with us ahead of time, all CSS and JavaScript must be in separate files, not in the head of your HTML or in the attributes inside it.](http://dh.newtfire.org/projectGuide.html)

**Comment by ebeshero** [comment]
I'm seconding @ajnewton1 here. Please separate the CSS from the HTML--it's in the interests of project longevity and accessibility. Read more about it from the w3c (WorldWide Web Consortium) here: https://www.w3.org/wiki/The_web_standards_model_-_HTML_CSS_and_JavaScript#Why_separate.3F
