### ISSUE TITLE
Flexboxes on Data Page

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#31]
I'm having some trouble getting my flexboxes to work properly on our [data](https://github.com/quantum-satire/warofcurrents/blob/e38e8094c09f022967f41b3d4809a2527a609e7b/website/data.html) page. I think I have everything marked correctly; I am trying to have three graphs displayed on one row along the page with some text beneath each one explaining what they show / mean. I have placeholder images and text for now.

Note: I have inline CSS ONLY for showing my code all on one page. They will be separate once I push the code to the server.

@ebeshero @ajnewton1

**Comment by ebeshero** [comment]
@quantum-satire Aha! I believe the problem is a mismatch in your `@id` values between the CSS and the HTML. In your HTML the div `@id` is set to "flexcontainer", but in the CSS you're using "flexContainer" with camelCase.

**Comment by helvitiis** [comment]
@ebeshero Oh my gosh. That fixed it. Thanks so much!! I was going crazy haha
