### ISSUE TITLE
Final Polishing and Adding Some Stuff

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#32]
Hey guys! I'm really glad I was able to work with you on this project this semester and I wanted to thank you for working so hard to make it great. 

By Thursday, we need to have a couple of things done:

- [x] Finish data tables
- [x] Consider changing the CSS of the data charts to not be responsive
- [x] Bolding the text when a checkbox is toggled on the outline page (I had done this previously Aaron so my code may still be there. If not, I can add this again!)
- [x] Adding descriptive text to the charts (I can also do this)

@ajnewton1 @Jamielynn92

**Comment by dotfig** [comment]
@quantum-satire Are you able to send me the graph you were working on. And I will adjust the checkboxes as well.

**Comment by helvitiis** [comment]
@ajnewton1 Do you mean the graph that's already on the site? I didn't get around to starting the other graph, but I did push [the file you can use with all of the documents to get the data using simple XPath without XSLT](https://github.com/quantum-satire/warofcurrents/blob/master/resources/documents.xml) if you need it.

**Comment by helvitiis** [comment]
@ajnewton1 I saw that the Outline page isn't functioning properly--when you click on the documents, the text does not show up. I'm not sure if you are in the middle of things here but just in case I thought I'd let you know!

**Comment by dotfig** [comment]
@quantum-satire Thats weird because it works perfectly fine for me... Try to check again

**Comment by helvitiis** [comment]
@ajnewton1 It works perfectly in Safari, but does not work in Chrome or Firefox... I cleared my cache files in both browsers to see if that would fix it and it did not. Are you working out of Safari as your main browser?

**Comment by dotfig** [comment]
@quantum-satire Yes it is the only browser I have. I am not sure why or how that is happening

**Comment by helvitiis** [comment]
@ajnewton1 It's working on Chrome now, but still not Firefox. I'm still playing with it and I'll keep you updated when I get it to be compatible--I was having this issue with another project too

**Comment by dotfig** [comment]
@quantum-satire I just added a chart to the data page. I also added github links to our names in the SSI

**Comment by dotfig** [comment]
@quantum-satire I can do the other graph. What do you want it to be?

**Comment by helvitiis** [comment]
@ajnewton1 I think another bar graph will be alright--we can keep it consistent that way and it will be easier than any other graph

**Comment by dotfig** [comment]
@quantum-satire What other data would you want it to show?

**Comment by helvitiis** [comment]
@ajnewton1 I think we wanted to log the companies that most appeared in the documents for the final graph--which can be done in a bar graph

**Comment by dotfig** [comment]
@quantum-satire Ill get to that right now
