### ISSUE TITLE
Possible Project Extension?

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#33]
@ebeshero I haven't had the time I wanted to to get the project to where it needs to be because of how hectic my exams schedule has been this week. Is it possible for our project to be due Friday by 11:59 PM rather than tonight? I feel bad asking for this so late.

**Comment by ebeshero** [comment]
@quantum-satire That's fine--and you may take until Saturday if you need to.

**Comment by helvitiis** [comment]
@ebeshero Thank you so much! I really appreciate this

**Comment by dotfig** [comment]
@quantum-satire @ebeshero Yes thank you so much! This is really helpful

**Comment by helvitiis** [comment]
@ajnewton1 @Jamielynn92 By midnight tonight, don't forget to send an email to Dr. B about evaluations:

> Each member of the project team must write a private e-mail message to the instructors (due by the project deadline) to describe what work you have contributed to the project and to evaluate the work done by your other team members. Your message should describe the contributions and responsibilities of each team member and comment on whether and how successfully these were fulfilled, in order for the instructors to fairly evaluate and issue project grades to the individual team participants.

I'll also communicate that the project is done and include the link for the group so you don't need to worry about it.

**Comment by Jamielynn92** [comment]
Which email is it?

**Comment by helvitiis** [comment]
@Jamielynn92 Did you find out her email? It's her Pitt email

**Comment by ebeshero** [comment]
@quantum-satire Is the team finished?

**Comment by helvitiis** [comment]
@ebeshero We should be now, sorry for the wait!

**Comment by ebeshero** [comment]
Thanks, @quantum-satire ! We'll start the rounds of commenting then for the project review.
