### ISSUE TITLE
Meeting This Week & Guidance On What to Do!

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#8]
Hey guys! I think we decided that we were going to meet this Friday if I'm not mistaken, however, Jamie and I have an hour set up each week between 12:30 - 1:30 on Fridays for tutoring and I wanted to make sure we would still be able to meet after 1:30 that day. I'm free the rest of the day but I'm not sure what everyone's schedules are like (I am also guilty of having forgotten to write down the meeting time we had originally agreed on for Friday, agh!) We may have to revert back to a Thursday meeting time. **Either way, please let me know by replying to this thread if a meeting time of 1:40 - 2:40 on Friday or 10:00 - 11:00 on Thursday would be more convenient for your schedules.** In our next meeting, I'll also be introducing some new ideas Dr. B and I discussed while I had a meeting with her last Thursday (I'm writing this here mainly to remind myself).

Also, before our next meeting, I am going to ask that we each find *at least* one article we feel would be a good body of text to code for the project (rather than four, let's start small and build from there). I wasn't very clear about this so I apologize! I'm going to be pushing some articles I find useful to the container folder, so you can look at those when they're up as some examples of what we'll be working with.

**CORRECTION: We can still meet this week on Friday from 1:00 - 2:00, but after this week we may need to go back to Thursdays.**

**Comment by Jamielynn92** [comment]
Friday’s I have a class to 2 so that wouldn’t work for me. I’m okay with coming early on Thursdays. Unless Aaron wants to join in our tutoring session. Lol

**Comment by helvitiis** [comment]
@Jamielynn92 I wouldn't have a problem with that, however, we'll be talking about meeting and project details rather than classwork and I'm afraid that would interfere with the time to go over the classwork!

**Comment by helvitiis** [comment]
I'm going to make a correction: Jamie, our tutoring hour for this week counted as today. We can still meet on Friday as a group if we need to, but we may have to switch to Thursdays after that!!

**Comment by Jamielynn92** [comment]
That’s fine with me.

**Comment by dotfig** [comment]
I won't be able to do Friday at that late time but I can do Thursday

**Comment by helvitiis** [comment]
Let's meet this Thursday and from now on stick to meeting on Thursdays at 10:00 am - 11:00 am!

**Comment by Jamielynn92** [comment]
I just have to remember to make an alarm. Cause I usually sleep in. Lol. But I shall try.

**Comment by dotfig** [comment]
Just making sure, I reread the main post and said that we can meet Friday. Then, I read the comments and we're meeting today. 

Question: When are we meeting? @quantum-satire

**Comment by Jamielynn92** [comment]
I think today. At least I hope so. I’m chilling in the commuter room cause I had to take me car to Hillview

**Comment by helvitiis** [comment]
@ajnewton1 We’re meeting today at 10:00, sorry about the confusion
