### ISSUE TITLE
Outline Summary for Meeting #2 and Homework

### ISSUE THREAD

**Issue by helvitiis** [quantum-satire/warofcurrents#9]
@ajnewton1 @Jamielynn92 Here is the outline summary of what we discussed today in our meeting:

https://github.com/quantum-satire/warofcurrents/blob/master/meetingNotes/meetingSummaries/notes2.md

This weekend I'm taking a break as much as I can to spend my birthday with family, but I'll be available to reply to any questions on GitHub if you tag me in a comment. Please don't hesitate to shout out if you want any guidance or need any help with anything at all!

Another thing--do we want to have a way to send quick messages to each other without having to use GitHub? I have Skype, LINE, Discord, Messenger (Facebook), Hangouts (Google)--you name it--we could choose to add each other on another platform for convenience. Let me know and I'll get something set up if this is what we want.

**Comment by Jamielynn92** [comment]
I have skype, FaceTime, I downloaded hangouts and messenger.

**Comment by helvitiis** [comment]
I personally use Skype a lot, and Messenger would be my second choice. I have no objection to using anything else, however

**Comment by helvitiis** [comment]
I'm setting up Skype for Business for us to try it out, it may work pretty well for what we need it for. I'll keep you guys updated!

**Comment by helvitiis** [comment]
I have Skype for Business up and running--I also added us into one group. It should come up for you automatically if you're able to download the program through [my.pitt.edu](https://my.pitt.edu/portal/server.pt/community/skype_for_business/946). Note that Skype for Business (Lync) is different than Skype, so you *will* need to download it separately from Skype. It gives us the ability to set meeting times and has a more comprehensive interface geared for small groups and businesses which we could use. We can always switch to something else if we feel the need to but I think this could work pretty well, especially if we need to have a meeting and one of us can't make it that day. It also allows for sharing screens and (I believe) remote desktop which could be a really useful feature for us.

**Comment by Jamielynn92** [comment]
I added it to my phone since I’m on it the most and don’t always have my computer with me.

**Comment by ebeshero** [comment]
Just an observation--we've been using Google Hangouts for the instructor-team meetings for this class, and the TEI Council uses Hangouts for its monthly meetings as well. It works for sharing desktops and views of applications (like oXygen) as we're working. I haven't investigated Skype for Business, since it's typically not readily available outside of Pitt--but you should feel free to use it! @ajnewton1 will be in a good position to compare experiences with the two systems. If you want me to join a meeting, though, I'll need to remember (or be prompted) to download the program via Pitt--It sounds like it's a pretty quick process?

**Comment by helvitiis** [comment]
@ebeshero It was very quick and easy! I’ve always had good experiences and little to no connection issues with Skype in the past which is why I thought we could give it a try—but if it’s more convenient for you, we could use Hangouts. I’ve only used Hangouts on their Desktop client, is there also an app?

**Comment by Jamielynn92** [comment]
There is an app. I downloaded it.
